src/main/java/kakaotech/bootcamp/respec/specranking/domain/auth/entity/OAuth.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/education/entity/Education.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/educationdetail/entity/EducationDetail.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/notification/entity/Notification.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/workexperience/entity/WorkExperience.java
엔티티에 기본 값이 있음으로써 혼동을 줄 수 있는 부분을 수정하였습니다.
예를 들어 직무에 INTERN이 기본 값이 었습니다.
기본 값을 두지 않고 필수적으로 입력할 수 있도록 하여 명확히 그 사람의 스펙임을 보장합니다.
=> fix: entity 기본 값 설정을 수정

src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/repository/SpecRepository.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/service/SpecService.java
프론트에서 active가 아닌 스펙을 수정 요청 하는 경우가 있다.
이를 백엔드 단에서 막기 위해 해당 부분 validation 기능을 추가한다.
마찬가지로 create도 active 스펙이 없을 경우 create가 가능하도록 로직을 수정한다.
=> feat: 스펙 create, put Active 여부에 따라 validation

src/main/java/kakaotech/bootcamp/respec/specranking/domain/user/controller/UserController.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/user/dto/UserVisibilityRequest.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/user/entity/User.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/user/service/UserService.java
스펙 공개여부 변경 기능 구현
<br/>
- 마이페이지에서 토글 버튼을 클릭함에 따라 User 테이블의 is_open_spec 필드를 변경하는 기능
- `PUT /api/specs/{specId}/visibility` -> `PATCH /api/users/me/visibility`로 API 명세서를 수정함
- DTO 작성함 (UserVisibilityRequest)
- UserController, UserService 작성함
- User 엔티티에 관련 생성자 추가함
- Postman 테스트 완료
<br/>
<br/>
<br/>
<br/>
=> feat: 스펙 공개여부 변경 기능 구현

src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/controller/CommentController.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/dto/ReplyPostResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/service/CommentService.java
대댓글 작성 기능 구현
<br/>
- DTO 작성함 (CommentPostRequest 재활용, ReplyPostResponse 생성)
- CommentController, CommentService 작성함
- 댓글 작성의 응답 DTO와 차이점 : replyCount 없음
- parentCommentId의 로직
> 댓글1 (depth 0, parentCommentId null)
>> 대댓글1 (depth 1, parentCommentId 댓글1.id)
>> 대댓글2 (depth 1, parentCommentId 댓글1.id)
- Postman 테스트 완료
<br/>
<br/>
<br/>
<br/>
=> feat: 대댓글 작성 기능 구현

src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/controller/CommentController.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/dto/CommentListResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/dto/CommentQueryDto.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/dto/ReplyQueryDto.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/repository/CommentRepository.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/repository/CommentRepositoryCustom.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/repository/CommentRepositoryImpl.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/repository/CustomPageImpl.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/comment/service/CommentQueryService.java
댓글 및 대댓글 목록 조회 기능 구현
<br/>
- CommentController : `GET /api/specs/{specId}/comments?page={page}&size={size}` 매핑
- CommentListResponse : 응답바디 DTO (isSuccess / message / data.comments / data.pageInfo)
- CommentQueryService : 본 기능에 대한 비즈니스 로직 작성
- CommentRepositoryCustom : Repository 인터페이스 생성
- CustomPageImpl : PageImpl을 상속받아 페이지네이션 커스텀함
- CommentQueryDto, ReplyQueryDto : QueryDSL에서 활용할 DTO 클래스 생성. 불필요한 필드까지 가져오지 않기 위함
- CommentRepositoryImpl : QueryDSL 작성
- 오프셋 기반 페이지네이션 구현
- 댓글은 최신순 정렬, 대댓글은 오래된순 정렬 
- 삭제된 최상위 댓글은 연관된 대댓글이 1개 이상일 때만 조회에 포함
- 삭제된 대댓글은 전부 조회에서 제외
- CommentRepositoryImpl 로직
- 페이지네이션 적용해 최상위 댓글 전부 조회
- 해당 페이지의 댓글들의 대댓글 전부 조회
- 각 댓글의 대댓글 개수 조회
- 대댓글을 부모 댓글별로 그룹화
- 최종 응답 데이터 조합
- 전체 댓글 개수 조회 (페이지네이션용)
- 전체 댓글+대댓글 개수 조회 (응답바디에 포함할 용도)
<br/>
<br/>
<br/>
<br/>
=> feat: 댓글 및 대댓글 목록 조회 기능 구현

src/main/java/kakaotech/bootcamp/respec/specranking/domain/bookmark/controller/BookmarkController.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/bookmark/dto/BookmarkListResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/bookmark/repository/BookmarkRepository.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/bookmark/service/BookmarkQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/bookmark/service/BookmarkService.java
즐겨찾기 해제 및 즐겨찾기 버튼 표시 안되는 문제 수정
<br/>
- 즐겨찾기 해제 오류
- RankingItem에 즐겨찾기 버튼이 포함되어 있다. 그런데 랭킹 조회 시 isBookmarked만 반환하고 bookmarkId를 반환하지 않아 `DELETE /api/bookmarks/{bookmarkId}` 호출 시 bookmarkId가 null인 상황이 발생한다.
- bookmarkId를 응답바디에서 반환하면 새로고침하지 않으면 즐겨찾기 등록/해제를 반복적으로 할 수 없다는 문제가 있다.
- DELETE도 POST처럼 `/api/bookmarks/specs/{specId}`로 변경하여 문제를 해결했다.
- 즐겨찾기 페이지에서 즐겨찾기 버튼 안 나타나는 문제
- 다른 페이지처럼 RankingItem 컴포넌트를 활용하는데 즐겨찾기 페이지에서만 즐겨찾기 버튼이 표시되지 않는다.
- userId를 응답바디에서 반환하지 않아 사용자를 인식할 수 없어 발생하는 문제였다.
- BE BookmarkListResponse에 userId 추가하여 문제를 해결했다.
<br/>
<br/>
<br/>
<br/>
=> fix: 즐겨찾기 해제 및 즐겨찾기 버튼 표시 안되는 문제 수정

src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/service/SpecDetailQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/user/controller/UserController.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/user/dto/UserDetailResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/user/service/UserService.java
사용자 스펙 공개여부와 타인의 스펙 상세정보를 조회할 수 없는 문제 해결 
<br/>
- 사용자 기본정보 조회 시 스펙 공개여부는 알 수 없는 문제 발생
- 해당 계정의 소셜페이지 접근 가능여부 판단 불가
- 사용자 기본정보 조회 dto 생성 (리팩토링) + isOpenSpec 필드 추가
- 타인의 스펙 상세정보를 조회할 수 없는 문제 발생
- 타인의 소셜페이지 접근 시도 시 '자신의 스펙만 조회할 수 있습니다.' 에러 메시지 반환
- 타인의 소셜페이지 접근 불가
- 자신의 스펙이 아니어도 로그인한 사용자이면 모두 스펙 상세정보를 조회할 수 있도록 수정함
<br/>
<br/>
<br/>
<br/>
=> fix: 사용자 스펙 공개여부와 타인의 스펙 상세정보를 조회할 수 없는 문제 해결 

src/main/java/kakaotech/bootcamp/respec/specranking/domain/auth/jwt/CookieUtils.java
쿠키 httponly false 설정 명시
<br/>
- 배포 환경에서 로그인 안 되는 문제로 CookieUtils 코드 수정함
- PC 버전에서는 로그인되지만 모바일에서는 여전히 로그인되지 않음
- CookieUtils 코드 리팩토링 및 httponly false 설정 명시함
<br/>
<br/>
<br/>
<br/>
- 🚨 로컬 테스트 시 수정해야 하는 부분
- `IS_SECURE = false;` 로 수정
- `SAME_SITE_CROSS_DOMAIN = "Lax";` 로 수정
- `DOMAIN = "localhost"';` 로 수정
=> fix: 쿠키 httponly false 설정 명시

src/main/java/kakaotech/bootcamp/respec/specranking/domain/auth/jwt/CookieUtils.java
도메인명 수정, isLocal 여부에 따른 변수 설정 추가
<br/>
- CookieUtils 도메인명 수정 : `dev.specranking.net` -> `.dev.specranking.net`
- CookieUtils에서 개발/운영 환경에 따른 변수 설정 추가 -> `IS_LOCAL` 변수만 true/false 변경해서 사용하면 됨
<br/>
<br/>
<br/>
<br/>
=> fix: 도메인명 수정, isLocal 여부에 따른 변수 설정 추가

src/main/java/kakaotech/bootcamp/respec/specranking/domain/ai/aiserver/MockAiServer.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/ai/dto/ai/mapping/AiDtoMapping.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/ai/dto/ai/request/AiPostResumeRequest.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/ai/dto/ai/request/AiPostSpecRequest.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/ai/dto/ai/response/AiPostResumeResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/ai/dto/web/response/WebPostResumeResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/dto/consume/ChatRelayConsumeDto.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/dto/produce/ChatProduceDto.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/dto/request/SocketChatSendRequest.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/dto/response/ChatListResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/dto/response/ChatRelayResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/handler/ChatWebSocketHandler.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/service/ChatQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/service/ChatService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chatparticipation/dto/response/ChatParticipationListResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chatparticipation/service/ChatParticipationService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/notification/dto/response/NotificationStatusResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/notification/service/NotificationService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/dto/request/PostSpecRequest.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/dto/response/RankingResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/dto/response/SearchResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/dto/response/SpecDetailResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/dto/response/SpecMetaResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/service/SpecDetailQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/service/SpecQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/service/SpecService.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/dto/SimpleResponseDto.java
dto를 모두 record로 변경한다.
- builder
set을 중간에 하나 빼먹을 위험이 존재한다.
- final 생성자 방식 
Jackson이 getter, setter에 의존하는 문제점이 존재한다.
따라서 isSuccess 필드가 success로 json이 나가는 문제점이 있다.
record 방식을 도입한다.
=> refactor: dto 모두 record로 변경

src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/constants/BookmarkMessages.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/controller/BookmarkController.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/dto/BookmarkCreateResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/dto/BookmarkListResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/repository/BookmarkRepository.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/repository/BookmarkRepositoryCustomImpl.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/service/BookmarkQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/service/BookmarkService.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/dto/ErrorResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/dto/SimpleResponseDto.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/exception/CustomException.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/exception/ErrorCode.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/exception/GlobalExceptionHandler.java
커스텀 예외 처리 추가, 즐겨찾기 등록.해제 기능 리팩토링
<br/>
- 커스텀 예외 처리 추가
- global/exception 패키지에 CustomException, ErrorCode 추가함
- global/dto 패키지에 ErrorResponse 추가함
- 에러 메시지는 ErrorCode에 모두 저장하면 됨
- 즐겨찾기 등록.해제 기능 리팩토링
- constants/BookmarkMessages에 성공 메시지 담아둠
- BookmarkController에 파라미터 관련 Validation 추가
- BookmarkCreateResponse를 @Data 선언 방식에서 record 클래스로 변환함
- BookmarkService에서 명확한 함수 분리 및 하드코딩 제거
<br/>
<br/>
<br/>
<br/>
=> refactor: 커스텀 예외 처리 추가, 즐겨찾기 등록.해제 기능 리팩토링

src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/SpecQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/common/config/CacheConfig.java
meta-data query cache-aside 전략 개발
meta-data의 경우 '잘 바뀌지 않는 쿼리' 이다.
또한 잠시 총 사용자의 수, 평균 점수가 정합성이 맞지 않아도 문제가 없다
따라서 ttl 기반의 cache-aside 전략이 어울린다.
이를 개발한다.
=> feat: meta-data query cache-aside 전략 개발

src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/dto/BookmarkCreateResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/dto/BookmarkListResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/comment/dto/CommentListResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/comment/dto/CommentPostResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/comment/dto/CommentUpdateResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/comment/dto/ReplyPostResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/exception/GlobalExceptionHandler.java
파라미터에 대한 예외처리 추가, bookmark와 comment 도메인에서 Boolean을 모두 boolean으로 수정
<br/>
- Controller에서 @PathVariable에 맞지 않는 타입이 들어오면 MethodArgumentTypeMismatchException 발생함
- 해당 예외처리를 GlobalExceptionHandler에 추가함
- Bookmark, Comment 도메인 내 dto에 선언된 Boolean을 모두 boolean으로 수정함
- dto를 record 클래스로 변경해서 이제 isSuccess가 success로 반환되는 문제가 발생하지 않음
- boolean은 true, false만 허용하지만 Boolean은 true, false, null을 허용해 더 명확한 것은 boolean 타입임
- Boolean이 boolean보다 차지하는 메모리가 큼. 성능적으로 boolean이 더 효율적
- Boolean은 참조타입, 128bit <-> boolean은 원시타입, 1bit
<br/>
<br/>
<br/>
<br/>
=> refactor: 파라미터에 대한 예외처리 추가, bookmark와 comment 도메인에서 Boolean을 모두 boolean으로 수정

src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/chat/handler/ChatWebSocketHandler.java
채팅 접속시 redis에 ip를 넣을때 ttl을 24시간으로 설정한다.
원래는 ttl이 존재하지 않았다.
하지만 ec2 서버가 모종의 이유로 종료되었을때 redis에 있는 ip를 제거할 수 없게 된다. 혹여나 그런 상황을 대비하여 24시간 ttl을 설정한다.
채팅을 오랫동안 하는 유저는 24시간 동안 채팅을 할 수 있으므로 24시간을 기준으로 한다.
=> feat: 채팅 접속시 redis에 ip를 넣을때 ttl을 24시간으로 설정한다.

src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/dto/request/PostSpecRequest.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/SpecService.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/infrastructure/redis/service/IdempotencyService.java
스펙 등록, 수정 멱등키를 이용해 멱등성 보장
스펙 페이지 입력, 수정에서 클릭을 빠르게 한다면, 멱등성이 보장되지 않는 문제가 발생할 수 있다.
사용자는 무의식적으로 마우스 클릭을 여러번 할 수 있다. 이럴때에 같은 여러 스펙이 생성되면 안된다.
이를 멱등키를 이용하여 하나만 생성함을 보장한다.
=> feat: 스펙 등록, 수정 멱등키를 이용해 멱등성 보장

src/main/java/kakaotech/bootcamp/respec/specranking/domain/social/bookmark/entity/Bookmark.java
bookmark에 user_id 기반 인덱스 설정
bookmark는 로그인 된 사용자를 기준으로 true, false 여부를 가져온다.
따라서 user_id를 인덱싱한다.
=> feat: bookmark에 user_id 기반 인덱스 설정

.gitignore, build.gradle, src/test/java/kakaotech/bootcamp/respec/specranking/domain/social/comment/repository/CommentRepositoryTest.java, src/test/java/kakaotech/bootcamp/respec/specranking/domain/social/comment/validator/CommentQueryValidatorTest.java, src/test/java/kakaotech/bootcamp/respec/specranking/domain/social/comment/validator/CommentValidatorTest.java, src/test/java/kakaotech/bootcamp/respec/specranking/fixture/RepositoryTestFixture.java, src/test/java/kakaotech/bootcamp/respec/specranking/fixture/TestConstants.java, src/test/resources/application-test.properties
comment 도메인의 validator, repository에 대한 테스트코드 작성
<br/>
- ⭐️⭐️⭐️ `build.gradle`에 코드를 추가했기 때문에 동기화 후 실행해야 정상 작동합니다.
- Validator 테스트코드
- Comment 도메인의 validator 메소드들에 대한 테스트 코드 작성
- Service단에서는 mockValidator를 주입했기 때문에 따로 검증이 필요하다. 예외 처리 부분도 많이 포함되어 있어 중요하다.
- `CommentQueryValidatorTest` : 2개 테스트 통과
- `CommentValidatorTest` : 6개 테스트 통과
- 중복되는 테스트 코드는 한 번만 작성함
- `validateReplyCreation` : 대댓글 생성 검증 성공, COMMENT_SPEC_MISMATCH, REPLY_DEPTH_EXCEEDED
- `validateCommentUpdateAndDeletion` : 댓글 수정 검증 성공, COMMENT_ACCESS_DENIED, COMMENT_ALREADY_DELETED
- Repository 테스트코드
- `findCommentsWithReplies` 메소드는 직접 작성한 QueryDSL 활용 메소드이기 때문에 테스트코드 작성이 필요하다.
- `fixture/TestConstants` : 필요한 상수 추가 선언
- `fixture/RepositoryTestFixture` : mock user/spec/comment 간단히 생성할 수 있도록 하는 클래스
- `CommentRepositoryTest` : 8개 테스트 통과
- …
=> test: comment 도메인의 validator, repository에 대한 테스트코드 작성

build.gradle, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/controller/SpecQueryController.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/entity/Spec.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/repository/SpecRepository.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/SpecQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/common/aop/timetrace/TimeTrace.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/common/aop/timetrace/TimeTraceAspect.java
getRankings 메서드를 쿼리 성능 개선한다.
1. countUsersHavingSpec의 경우 호출 시 공통된 값을 가져옵니다. 이를 공통으로 분리하여 중복된 쿼리를 제거합니다.
평균 1200ms -> 200ms로 개선
2. 스펙이 존재하는 유저 수를 유저테이블에서 스펙 테이블을 조인하고 찾아내는 구조였습니다.
이를 스펙 테이블을 기준으로 distinct 유저를 사용하도록 변경합니다.
이렇게 진행하면 조인을 하지 않으므로 성능이 개선됩니다.
평균 200ms -> 120ms 개선되었습니다.
총 1200ms -> 120ms로 개선, 캐싱이 아닌 쿼리만으로 90% 개선 완료.
=> feat: getRankings 쿼리 성능 개선

src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/dto/cache/CachedMetaResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/dto/cache/CachedRankingResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/SpecQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/cache/SpecCacheRefreshService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/refresh/SpecRefreshQueryService.java
선제적 갱신을 PER 알고리즘으로 고도화 합니다.
전의 캐싱의 경우 단순 jitter를 적용한 선제적 갱신이었습니다.
이를 선제적 갱신에서 효과적인 알고리즘으로 알려진 PER 알고리즘으로 전환합니다.
beta와 같은 파라미터로 선제적 갱신을 얼마나 자주 적용할지 선택할 수 있습니다.
또한 캐시를 계산하기 위해 걸린 "계산 시간"을 기반으로 확률적으로 캐싱 refresh을 적용하여 효율적인 선제적 갱신이 가능합니다.
=> feat: Cached jitter를 이용한 선제적 갱신, 논문 내용의 PER 알고리즘으로 고도화

src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/dto/response/RankingResponse.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/SpecQueryService.java
프론트에서 상태관리하는 isBookmarked 필드를 제거한다.
프론트에서 로그인할때 자신의 즐겨찾기 목록을 가져온다.
따라서 getRankings에서 즐겨찾기 목록을 "계속해서 api 호출할 필요가 없다."
즉 프론트에서 상태관리를 한다면 로그인 할때에만 db에서 즐겨찾기 목록을 가져오고, 그뒤로는 bookmark에 대한 db 접근을 하지 않는다.
따라서 isBookmarked 필드를 제거한다.
=> fix(getRankings): 프론트에서 상태관리하는 isBookmarked 필드를 제거한다.

src/main/java/kakaotech/bootcamp/respec/specranking/global/exception/GlobalExceptionHandler.java, src/test/java/kakaotech/bootcamp/respec/specranking/domain/social/comment/CommentIntegrationTest.java, src/test/java/kakaotech/bootcamp/respec/specranking/fixture/RepositoryTestFixture.java, src/test/java/kakaotech/bootcamp/respec/specranking/fixture/TestConstants.java
Comment 도메인 integration 테스트코드 작성
<br/>
- 통합테스트에서 다루는 케이스
- 핵심 성공 시나리오
- 주요 실패 시나리오
- 전체 플로우 검증
- 데이터베이스 상태 검증
- @Transactional 어노테이션 : 각 테스트 후 자동으로 롤백해줌
- 비즈니스 로직에서 많이 사용되는 `SecurityContextHolder` 관련 처리
- `CommentIntegrationTest` 내에 `createAuthentication` 메소드를 생성하여 권한 부여
- `CommentIntegrationTest` : 13개 테스트 통과
- 댓글 작성 통합 테스트
- 대댓글 작성 통합 테스트
- 댓글 수정 통합 테스트
- 댓글 삭제 통합 테스트
- 댓글 목록 조회 통합 테스트
- 전체 플로우 통합 테스트
- Comment 도메인의 최종 테스트 커버리지
- 클래스 기준 : 96%
- 메서드 기준 : 97%
- 줄 기준 : 99%
- 브랜치 기준 : 91%
- entity 관련 테스트코드를 작성하지 않아 커버리지가 90%대임
<br/>
<br/>
<br/>
<br/>
=> test: Comment 도메인 integration 테스트코드 작성

src/main/java/kakaotech/bootcamp/respec/specranking/domain/auth/config/OAuth2RedisConfig.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/auth/config/SecurityConfig.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/auth/repository/CustomAuthorizationRequestRepository.java
분산환경을 위해 redis에 소셜로그인 요청 정보 저장
<br/>
- 분산 환경으로 이전 후 로그인이 성공했다가 실패했다가 하는 문제 발생함
- 소셜로그인 요청 정보를 가진 서버에서 카카오 페이지를 갔다가 다른 서버로 돌아올 경우, 요청 정보를 가지고 있지 않아 문제가 발생하는 것으로 예상됨
- 어떤 서버에서든 요청을 받을 수 있도록 Redis에 소셜로그인 요청 정보를 1초 동안 저장하도록 구현함
<br/>
<br/>
<br/>
<br/>
=> feat: 분산환경을 위해 redis에 소셜로그인 요청 정보 저장

src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/chat/repository/ChatRepositoryImpl.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/chat/chat/service/ChatQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/repository/SpecRepositoryImpl.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/SpecQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/domain/spec/spec/service/refresh/SpecRefreshQueryService.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/common/util/cursor/CursorPagination.java, src/main/java/kakaotech/bootcamp/respec/specranking/global/common/util/cursor/CursorUtils.java
cursor 기반 페이지네이션 유틸 클래스 작성하여 역할 분리
chat과 spec에서 커서 기반 페이지네이션을 사용한다.
이를 util 클래스로 작성하여 페이지네이션 정보를 가져오는 역할을 분리한다.
=> refactor: cursor 기반 페이지네이션 유틸 클래스 작성하여 역할 분리
